---
title: "Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
   data: "/work/gladieux/magMax_project/4_Orthologie/1_rawdata_without_Transcript/Results_Dec03/test/gene.count.csv"
   dataH: "/work/gladieux/magMax_project/Old_Analysis/4_Orthologie/6_effecteurMax_pangenome/hote_isolat.csv"
output:
  html_document:
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```


```{r data, echo = FALSE, warning=FALSE,tidy=TRUE, comment = NA}
library('DT')
minGroupe <- 5
data <- read.table(params$data,head = T,sep = '\t')
rownames(data) <- data$Groupe
Groupe <- data$Groupe
data <- data [2:ncol(data)]
correction <- data == '1*'
data[correction] <- 1
for (colonne in colnames(data))
{
  data[,colonne] <- as.character(data[,colonne])
}
abs <- data == '0'
data[abs] <- 'Absent'
pres <- data !=  'Absent' 
data[pres] <- 'Présent'
data <- cbind(Groupe,data)

dataHote <- read.table(params$dataH,sep = '\t')
rownames(dataHote) <- dataHote$V1
dataHote <- data.frame(t(dataHote))
dataH <- c()
dataname<- c()
for (elt in colnames(data))
{
  if (elt != 'Groupe' && elt %in% colnames(dataHote))
  {
    dataname <- c(dataname,elt)
  }
  dataH <- c(dataH,as.character(dataHote[2,elt]))
}
dataH <- data.frame(t(dataH))
colnames(dataH) <- dataname
rownames(dataH) <- 'Phenotype'
rownames(data) <- data$Groupe
data <- data[colnames(dataH)]
# data <- data[,2:ncol(data)]
data <- rbind(data,dataH)
data <-  data.frame(t(data))
phenotype <- unique(data$Phenotype)
NombrePhenotypeUtilisée = 0
for ( elt in phenotype)
{
  select <- data$Phenotype == elt
  nbPheno <- as.numeric(table(select)[2])
  if (nbPheno >= minGroupe)
  {
    NombrePhenotypeUtilisée = NombrePhenotypeUtilisée+1
  }
  
}


```

&nbsp;

##Summary

&nbsp;

Summary             |       Nombre                                                             
------------ | --------------------------------------------------------------------------
Groupe d'orthologue d'effecteur MAX  | `r ncol(data)-1` 
Taille minimale d'un groupe          | `r minGroupe` 
Nombre de phenotypes traités         | `r NombrePhenotypeUtilisée` 
Correction effectuer par le script   | `r table(correction)[2]` 
Tests statistiques effectués         | `r (ncol(data)-1)*NombrePhenotypeUtilisée`

---- 

##Analyse statistique (Chi2){.tabset}

###Tableau Récapitulatif

&nbsp;


```{r table, echo = FALSE, warning=FALSE,tidy=TRUE, comment = NA}

test_association_Pheno_Effecteur <- function(data,minGroupe,print,tableau)
{
  groupe.table <- c()
  groupe.done <- c()
  names <- c('Groupe','Hote','p-value','Présent_hote','Absent_Hote','Present_Other','Absent_Other')
  tableData <- data.frame(names, row.names = names)
  phenotype <- unique(data$Phenotype)
  for ( elt in phenotype)
  {
    select <- data$Phenotype == elt
    nbPheno <- as.numeric(table(select)[2])
    if (nbPheno >= minGroupe) 
    {
      newPheno <- rep("Z-Other",nrow(data))
      newPheno[select] <- elt
      dataElt <- data
      dataElt$Phenotype <- newPheno
      for (groupe in colnames(data))
      {
        if (groupe != 'Phenotype')
        {
          table <- table(dataElt[,groupe],dataElt$Phenotype)  
          test <- chisq.test(table)
          if (length(table) == 2 && length(rownames(table)) >2)
           {
            score <- c(groupe,elt,as.numeric(formatC(test$p.value,format='e',digits = 1)),table[1],0,table[2],0)
           }
          if (length(table) == 4)
          {
            pvalue <- as.numeric(formatC(test$p.value,format='e',digits = 1)) 
            score <- c(groupe,elt,pvalue,table[2],table[1],table[4],table[3]) 
            if (pvalue < 1e-5 && !(groupe %in% groupe.done))
            {
              tableAll <- table(data[,groupe],data$Phenotype)
              Présent <- c()
              Absent <- c()
              for (IsolatName in colnames(tableAll))
              {
                select <- data[,"Phenotype"] == IsolatName
                dataTest <- data[select,]
                select <- dataTest[,groupe] == "Présent"
                sample <- paste(rownames(dataTest)[select], collapse = ', ')
                newhote <- paste(IsolatName,sample,sep = ' : ')
                Présent <- c(Présent,newhote)
                select <- dataTest[,groupe] == "Absent"
                sample <- paste(rownames(dataTest)[select], collapse = ', ')
                newhote <- paste(IsolatName,sample,sep = ' : ')
                Absent <- c(Absent,newhote)
              }
              groupe.table <- rbind(groupe.table,c(groupe,'Présent',tableAll[2,],Présent),c(groupe,'Absent',tableAll[1,],Absent))
              groupe.done <- c(groupe.done,groupe)
            }
          }
          else 
          {
            score <- 'error'
          }
          if (score != 'error')
          {
            tableData <- data.frame(tableData,score,row.names = c('Groupe','Hote','p-value','Présent_hote','Absent_Hote','Present_Other','Absent_Other'))
          }
          if (print == TRUE)
          {
            print(paste('Groupe : ',groupe))
            print(paste('Phenotype : ',elt))
            print(test)
            print(table)
            print('-------------------------------------------------------------------------', quote = F, type="html")
          }
        }
      }
    }
  } 
  if (tableau == TRUE)
  {
    return(tableData)
  }
  if (tableau == FALSE)
  {
    groupe.table <- data.frame(groupe.table)
    colnames(groupe.table) <- c("Orthogroups",'Statuts',colnames(groupe.table)[3:(ncol(groupe.table)-1)],'info')
    return(groupe.table)
  }
}

tableData <- test_association_Pheno_Effecteur(data,minGroupe,FALSE,TRUE)
rownames(tableData) <- tableData$names
tableData <-  data.frame(t(tableData[,2:ncol(tableData)]))
datatable(tableData,extensions = 'Buttons',rownames = NA,options = list(dom = 'Blfrtip',buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
```


-----

###Résultats bruts

```{r stat, echo = FALSE, warning=FALSE,tidy=TRUE, comment = NA}
tableData <- test_association_Pheno_Effecteur(data,minGroupe,TRUE,TRUE)
```

------

&nbsp;

## Données brutes

&nbsp;

```{r données Brutes, echo = FALSE, warning=FALSE,tidy=TRUE, comment = NA}

NbPheno <- length(unique(t(dataH))) 

target <- c((NbPheno+4):(NbPheno*2+3))

groupe.table <- test_association_Pheno_Effecteur(data,minGroupe,FALSE,FALSE)

datatable(cbind(' ' = '&oplus;',groupe.table), escape = -2,
          options = list(
            columnDefs = list(
              list(visible = FALSE, targets = target),
      list(orderable = FALSE, className = 'details-control', targets = 1)
    )
  ),
  callback = JS("
  table.column(1).nodes().to$().css({cursor: 'pointer'});
  var format = function(d) {
    var start = (d.length/2) +2
    var end = d.length 
    var c = '<div style=\"background-color:#eee; padding: .5em;\"> '
    while (start < end) 
    {
      var c = c + '<br/>'+ d[start] +'<br/>'
      start ++
    }
    var c = c + '</div>'
    return c;
  };
  table.on('click', 'td.details-control', function() {
    var td = $(this), row = table.row(td.closest('tr'));
    if (row.child.isShown()) {
      row.child.hide();
      td.html('&oplus;');
    } else {
      row.child(format(row.data())).show();
      td.html('&CircleMinus;');
    }
  });"
))
#datatable(groupe.table,extensions = 'Buttons',rownames = NA,options = list(dom = 'Blfrtip',buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
```
